### PR TITLE
Add Missing invoice states

### PR DESCRIPTION
**Pull request by RoelandMatthijssens**
This PR also changes the invoice states in the enum to lower case.

### CODE REVIEW

**Comment by freeduerinckx** [comment]
@Kjoep has this any impact on Jim?
@JanJoris has this any impact on stievie?
@smaris has this any impact on mv-web?

I'll approve if it's safe for the web components. Invoices aren't used in the apps so we're ok for those.

**Comment by smaris** [comment]
Yes: https://github.com/vikingco/mv-web/blob/master/website/constants.py#L11. Will need to be transformed to uppercase in the `InvoiceSettingsSerializer` of mv-web.

**Comment by Kjoep** [comment]
Yes.  This will break our invoice overview and 'pay an invoice' pages.
I made a ticket here: https://vikingco.atlassian.net/browse/JMGR-317
We'll support both styles initially so you're unblocked.

**Comment by RoelandMatthijssens** [comment]
Jim should be compatible with https://vikingco.atlassian.net/browse/JMGR-317 finished
MV-web should be compatible with https://vikingco.atlassian.net/browse/MVP-15934 finished
stievie should be compatible with https://vikingco.atlassian.net/browse/UWA-638 finished

As far as i'm concerned this can be merged now!

**Pull request merged**
