### PR TITLE
Add due_amount as field to invoice

### PR DESCRIPTION
**Pull request by Timvde**
https://vikingco.atlassian.net/browse/UWA-924

### CODE REVIEW

**Comment by Timvde** [comment]
@JanJoris @daneov @Kjoep This is an addition only. Is this okay for you?

**Comment by Timvde** [comment]
Pull request for showing partially paid invoices (this change) is in https://github.com/vikingco/unleashed-web-api/pull/779. The `pay` call doesn't yet support partially paid invoices though (UWA-934), but it should be pretty easy too.

**Comment by bmoelans** [comment]
@joen93 do you see any issue in app for this extra field, if no I merge

**Comment by joen93** [comment]
@bmoelans No issue for us, can be merged 👍

**Comment by daneov** [comment]
I'd use `amount_due` though. Not because their naming sucks that ours has to as well, right? 😋 

Seems to be more widely used as well, since a quick Google returns only one result on the first page I receive actually phrased `due amount`, all the others are `amount due`.

**Comment by Kjoep** [comment]
@daneov  A bit too late; but indeed @daneov is right.  'Amount due' is the term i'm used to hearing, too.

**Comment by daneov** [comment]
@Kjoep Too late? Just change it 😅 plus, I'm still within 24h of being tagged.

**Comment by bmoelans** [comment]
extra advantage, output is ordered alphabetical, so `amount` is close to `amount_due`.
UWA ticket is not in master so we still can easily adapt.
@Timvde will you follow up?

**Comment by Timvde** [comment]
@bmoelans I'm on holiday for the coming week, feel free to take over my PR.

**Pull request merged**
