### PR TITLE
Add order type

### PR DESCRIPTION
**Pull request by nielsvanoch**
For reviewers:
* I made the type an enum, although there could be new types in future. Mostly because we want to use the type to determine state information, so a freeform field seems iffy.
* Not all types from SBSS are here. The ones I left out (like the silent imsi etc) are ones we don't need to expose to the user.
* This also implies the field is optional

@freeduerinckx @bmoelans @Kjoep and anyone else: agreed?

### CODE REVIEW

**Comment by Kjoep** [comment]
it would definitely be helpful to us, as we currently 'guess' the order type based on the content of the order.  But are we sure sbss even has such a concept? I would check that first.

(silent imsi is just swap_sim)

**Comment by nielsvanoch** [comment]
The ones in the enum now are all things from SBSS (I based myself on their list to create it). And it's returned in the SBSS API as well.

Silent IMSI has a separate process from the regular swap. It's not the same type.

**Comment by Kjoep** [comment]
Okay -- amazed by the silent imsi then :)  Shouldn't we add an 'unknown' entry then to be able to map future types? or do you plan on just ignoring them?

**Comment by nielsvanoch** [comment]
My idea was to leave it empty for unknowns/irrelevants, and if there are some we want to support later, we add them to the enum.

**Comment by Kjoep** [comment]
Cool.  That can work, methinks.

**Pull request merged**
