### PR TITLE
Update sim swap endpoint

### PR DESCRIPTION
**Pull request by Timvde**
Add block_sim parameter, remove redirect_url

https://vikingco.atlassian.net/browse/UWA-146

### CODE REVIEW

**Comment by freeduerinckx** [comment]
@Kjoep @smaris can you check if this is ok?

**Comment by smaris** [comment]
Just checked, ok for me, not yet transferred to MV-WEB

**Comment by Kjoep** [comment]
I kind of get the description for block_sim, since we talked about it.  But coming from nowhere, that description doesn't make much sense.  If it _needs_ to be true, why have it at all?

Maybe we can make it something like 'block the current sim after requesting a swap.  For theft or loss, this parameter is ignored and the sim is blocked anyway'
Or something :)

**Comment by Timvde** [comment]
We found it more obvious behaviour to give a 400 when `block_sim` is `false` when it shouldn't be, than to silently ignore the parameter. Maybe reverse the wording? "`false` is only a valid value when the reason for the sim swap is not theft or loss"?

**Pull request merged**
